name: hot_recharge
description: a hot-recharge plugin for mobile airtime topup and zesa recharge
version: 1.0.1
homepage: https://github.com/DonnC/hot-recharge-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  uuid: ^3.0.6
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter: